######################################################################
# Automatically generated by qmake (3.0) jue. oct. 5 19:21:25 2017
######################################################################

TEMPLATE = app
TARGET = linux
INCLUDEPATH += .

# Input
HEADERS += chipset/adxl34x.h input/adxl34x.h \
    ../standalone/ADXL345.h
SOURCES += chipset/adxl34x-i2c.c chipset/adxl34x-spi.c chipset/adxl34x.c \
    ../standalone/ADXL345.c
